# Generated by Django 3.2.4 on 2021-11-08 14:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория имя')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='*')),
                ('img', models.ImageField(upload_to='cat_imgs', verbose_name='Категория Фото')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название статьи')),
                ('subtitle', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(verbose_name='*')),
                ('author', models.CharField(max_length=50, verbose_name='Статья Афтори')),
                ('date', models.DateField(auto_now=True, verbose_name='Дата Отправки')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryies', to='languae.categorys')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
