# Generated by Django 3.2.4 on 2021-11-08 14:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLanguaesubtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLanguaetitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название статьи')),
            ],
        ),
        migrations.CreateModel(
            name='CategoriyLanguae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='категории имя')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Katigoriya Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='*')),
                ('img', models.ImageField(upload_to='cat_imgs', verbose_name='Rasim')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='main.categoriylanguae')),
            ],
            options={
                'verbose_name': 'Katigoriya',
                'verbose_name_plural': 'Katigoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Maqola nomi')),
                ('subtitle', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(verbose_name='*')),
                ('author', models.CharField(max_length=50, verbose_name='Maqola aftori')),
                ('date', models.DateField(auto_now=True, verbose_name='Joylangan sanasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryies', to='main.category')),
                ('lang_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langus', to='main.categoriylanguae')),
                ('lang_subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='main.articlelanguaesubtitle')),
                ('lang_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='main.articlelanguaetitle')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
