# Generated by Django 3.2.4 on 2021-11-03 17:19

from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Katigoriya slug')),
                ('img', models.ImageField(upload_to='cat_imgs/', verbose_name='Katigriya rasmi')),
            ],
            options={
                'verbose_name': 'Katigoriya',
                'verbose_name_plural': 'Katigoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='*')),
                ('author', models.CharField(max_length=50, verbose_name='Maqola aftori')),
                ('date', models.DateField(auto_now=True, verbose_name='Joylangan sanasi')),
                ('post_views', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoryies', to='main.category')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
