# Generated by Django 3.2.4 on 2021-11-02 18:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='subtitle',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
