# Generated by Django 3.2.4 on 2021-11-07 17:30

import ckeditor.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2021, 11, 7, 17, 30, 56, 972682, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
