# Generated by Django 3.2.4 on 2021-11-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211102_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.AddField(
            model_name='articletranslation',
            name='slug',
            field=models.SlugField(default=0, verbose_name='*'),
            preserve_default=False,
        ),
    ]
