# Generated by Django 3.2.4 on 2021-11-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211104_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(default=1, upload_to='cat_imgs/', verbose_name='Katigoriya Rasmi'),
            preserve_default=False,
        ),
    ]
