# Generated by Django 3.2.4 on 2021-11-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211104_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cat_imgs/', verbose_name='Rasm'),
        ),
    ]
