# Generated by Django 3.2.4 on 2021-11-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post_views',
        ),
    ]
